# -*- coding: utf-8 -*-
"""데엔 project1 MongoDB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKMTUxt4n17524qmO1h_mXDnWqwXyWpA
"""

!pip install pymongo -q

import json
from datetime import datetime
from pymongo import MongoClient

# MongoDB Atlas 연결
client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

with open("reviews.json", "r", encoding="utf-8") as f:
    data = json.load(f)

reviews = data["reviews"]
print(f"총 {len(reviews)}개 리뷰 로드 완료")

# option 파싱 함수
def parse_option(option_str):
    if option_str and "·" in option_str:
        parts = option_str.split("·")
        return parts[0].strip(), parts[1].strip()
    return None, None

preprocessed = []
for r in reviews:
    if not r.get("review_text"):
        continue

    # 0점->null처리
    actual_rating = None if r.get("rating") == 0.0 else r.get("rating")

    # 날짜 문자열을 datetime 객체로 변환
    date_obj = None
    if r.get("date"):
        date_obj = datetime.strptime(r["date"], "%Y-%m-%d")

    color, size = parse_option(r.get("option"))

    # 계층 구조로
    preprocessed.append({
        "product_id":         r["product_id"],
        "review_id":          r["review_id"],
        "date":               date_obj,
        "rating":             actual_rating,
        "purchase_info": {
            "option_raw":     r.get("option"),
            "color":          color,
            "size":           size,
        },
        "user_info": {
            "encrypted_id":   r["encrypted_user_id"],
            "nickname":       r["reviewer_nickname"],
            "level":          r["reviewer_level"],
            "gender":         r["reviewer_gender"],
            "height_cm":      r["reviewer_height_cm"],
            "weight_kg":      r["reviewer_weight_kg"],
        },
        "review_data": {
            "type":           r["review_type"],
            "text":           r["review_text"],
            "has_photo":      len(r.get("photo_urls", [])) > 0,
            "photo_urls":     r.get("photo_urls", []),
            "like_count":     r["like_count"],
        }
    })

print(f"전처리 완료 (빈 텍스트 제외): {len(preprocessed)}개")


db.reviews.insert_many(preprocessed, ordered=False)
print(f"{len(preprocessed)}개 삽입 완료")

# 인덱스 설정
db.reviews.create_index("product_id")
db.reviews.create_index("rating")
db.reviews.create_index("date")
db.reviews.create_index([("product_id", 1), ("rating", -1)])
db.reviews.create_index([("product_id", 1), ("purchase_info.size", 1)])

# text index
db.reviews.create_index([("review_data.text", "text")])
print("인덱스 및 텍스트 인덱스 설정 완료")

import json
from pymongo import MongoClient

client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

with open("product_details.json", "r", encoding="utf-8") as f:
    data = json.load(f)

product = data["product_detail"]

result = db.products.update_one(
    {"product_id": product["product_id"]},
    {"$set": product},
    upsert=True
)

if result.upserted_id:
    print(f"새로 삽입 완료: {product['product_id']}")
else:
    print(f"업데이트 완료: {product['product_id']}")

import json
import os
from pymongo import MongoClient

# Atlas 연결
client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

product_files = [
    "202620_product_details.json",
    "903340_product_details.json",
    "1420730_product_details.json",
    "1841764_product_details.json",
    "1848166_product_details.json",
    "1999668_product_details.json",
    "1999677_product_details.json",
    "4314937_product_details.json",
    "4874594_product_details.json",
    "4956002_product_details.json",
]

print("=== products 적재 ===")
for filepath in product_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    product = data["product_detail"]
    result = db.products.update_one(
        {"product_id": product["product_id"]},
        {"$set": product},
        upsert=True
    )
    status = "삽입" if result.upserted_id else "업데이트"
    print(f" [{status}] {product['product_id']} - {product['product_name']}")


review_files = [
    "202620_reviews.json",
    "903340_reviews.json",
    "1420730_reviews.json",
    "1841764_reviews.json",
    "1848166_reviews.json",
    "1999668_reviews.json",
    "1999677_reviews.json",
    "4314937_reviews.json",
    "4874594_reviews.json",
    "4956002_reviews.json",
]

# option 파싱 함수
def parse_option(option_str):
    if option_str and "·" in option_str:
        parts = option_str.split("·")
        return parts[0].strip(), parts[1].strip()
    return None, None

# reviews 컬렉션 적재
print("\n=== reviews 적재 ===")
for filepath in review_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    reviews = data["reviews"]
    cleaned = []
    for r in reviews:
        color, size = parse_option(r.get("option"))
        cleaned.append({
            "product_id":         r["product_id"],
            "review_id":          r["review_id"],
            "encrypted_user_id":  r["encrypted_user_id"],
            "reviewer_nickname":  r["reviewer_nickname"],
            "date":               r["date"],
            "rating":             r["rating"],
            "option":             r.get("option"),
            "color":              color,
            "size_purchased":     size,
            "reviewer_level":     r["reviewer_level"],
            "reviewer_gender":    r["reviewer_gender"],
            "reviewer_height_cm": r["reviewer_height_cm"],
            "reviewer_weight_kg": r["reviewer_weight_kg"],
            "review_type":        r["review_type"],
            "review_text":        r["review_text"],
            "photo_urls":         r.get("photo_urls", []),
            "has_photo":          len(r.get("photo_urls", [])) > 0,
            "like_count":         r["like_count"],
        })

    db.reviews.insert_many(cleaned, ordered=False)
    print(f" {filepath} → {len(cleaned)}개 삽입")

print(f"\n=== 최종 확인 ===")
print(f"products 총 문서 수: {db.products.count_documents({})}")
print(f"reviews 총 문서 수:  {db.reviews.count_documents({})}")

target_product_ids = [
    "324416",
    "540421",
    "996499",
    "1982990",
    "2034137",
    "2035287",
    "2122566",
    "2442409",
    "3083117",
    "3727165",
    "4587753"
]

result = db.reviews.delete_many({
    "product_id": {"$in": target_product_ids}
})

print(f"✅ 삭제된 리뷰 수: {result.deleted_count}")

import json
import zlib
from datetime import datetime
from pymongo import MongoClient

# ── 1. Atlas 연결
client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

# ── 2. 추가 product 파일 목록
product_files = [
    "324416_product_details.json",
    "540421_product_details.json",
    "996499_product_details.json",
    "1982990_product_details.json",
    "2034137_product_details.json",
    "2035287_product_details.json",
    "2122566_product_details.json",
    "2442409_product_details.json",
    "3083117_product_details.json",
    "3727165_product_details.json",
    "4587753_product_details.json"
]

# ── 3. products 적재
print("=== products 적재 ===")
for filepath in product_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    product = data["product_detail"]
    result = db.products.update_one(
        {"product_id": product["product_id"]},
        {"$set": product},
        upsert=True
    )
    status = "삽입" if result.upserted_id else "업데이트"
    print(f"✅ [{status}] {product['product_id']} - {product['product_name']}")

# ── 4. 추가 review 파일 목록
review_files = [
    "324416_reviews.json",
    "540421_reviews.json",
    "996499_reviews.json",
    "1982990_reviews.json",
    "2034137_reviews.json",
    "2035287_reviews.json",
    "2122566_reviews.json",
    "2442409_reviews.json",
    "3083117_reviews.json",
    "3727165_reviews.json",
    "4587753_reviews.json"
]

# ── 5. option 파싱 함수
def parse_option(option_str):
    if option_str and "·" in option_str:
        parts = option_str.split("·")
        return parts[0].strip(), parts[1].strip()
    return None, None

# ── 6. reviews 적재
print("\n=== reviews 적재 ===")
for filepath in review_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    reviews = data["reviews"]
    cleaned = []
    for r in reviews:
        if not r.get("review_text"):
            continue
        color, size = parse_option(r.get("option"))
        actual_rating = None if r.get("rating") == 0.0 else r.get("rating")
        date_obj = None
        if r.get("date"):
            date_obj = datetime.strptime(r["date"], "%Y-%m-%d")

    cleaned.append({
    "product_id":   r["product_id"],
    "review_id":    r["review_id"],
    "date":         date_obj,
    "rating":       actual_rating,

    "purchase_info": {
        "option_raw": r.get("option"),
        "color":      color,
        "size":       size,
    },

    "user_info": {
        "encrypted_id": r["encrypted_user_id"],
        "nickname":     r["reviewer_nickname"],
        "level":        r["reviewer_level"],
        "gender":       r["reviewer_gender"],
        "height_cm":    r["reviewer_height_cm"],
        "weight_kg":    r["reviewer_weight_kg"],
    },

    "review_data": {
        "type":       r["review_type"],
        "text":       zlib.compress(r["review_text"].encode("utf-8")),
        "has_photo":  len(r.get("photo_urls", [])) > 0,
        "photo_urls": r.get("photo_urls", []),
        "like_count": r["like_count"],
    }
})

    if cleaned:
        db.reviews.insert_many(cleaned, ordered=False)
    print(f"✅ {filepath} → {len(cleaned)}개 삽입")

# ── 7. 최종 확인
print(f"\n=== 최종 확인 ===")
print(f"products 총 문서 수: {db.products.count_documents({})}")
print(f"reviews 총 문서 수:  {db.reviews.count_documents({})}")

import json
import zlib
from datetime import datetime
from pymongo import MongoClient

client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

product_files = [
    "324416_product_details.json",
    "540421_product_details.json",
    "996499_product_details.json",
    "1982990_product_details.json",
    "2034137_product_details.json",
    "2035287_product_details.json",
    "2122566_product_details.json",
    "2442409_product_details.json",
    "3083117_product_details.json",
    "3727165_product_details.json",
    "4587753_product_details.json"
]

print("products 적재")
for filepath in product_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    product = data["product_detail"]

    result = db.products.update_one(
        {"product_id": product["product_id"]},
        {"$set": product},
        upsert=True
    )

    status = "삽입" if result.upserted_id else "업데이트"
    print(f"[{status}] {product['product_id']} - {product['product_name']}")

review_files = [
    "324416_reviews.json",
    "540421_reviews.json",
    "996499_reviews.json",
    "1982990_reviews.json",
    "2034137_reviews.json",
    "2035287_reviews.json",
    "2122566_reviews.json",
    "2442409_reviews.json",
    "3083117_reviews.json",
    "3727165_reviews.json",
    "4587753_reviews.json"
]

def parse_option(option_str):
    if option_str and "·" in option_str:
        parts = option_str.split("·")
        return parts[0].strip(), parts[1].strip()
    return None, None

print("\nreviews 적재")
for filepath in review_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    reviews = data["reviews"]
    cleaned = []

    for r in reviews:
        if not r.get("review_text"):
            continue

        color, size = parse_option(r.get("option"))
        actual_rating = None if r.get("rating") == 0.0 else r.get("rating")

        date_obj = None
        if r.get("date"):
            try:
                date_obj = datetime.strptime(r["date"], "%Y-%m-%d")
            except ValueError:
                date_obj = None

        cleaned.append({
            "product_id": r["product_id"],
            "review_id": r["review_id"],
            "date": date_obj,
            "rating": actual_rating,

            "purchase_info": {
                "option_raw": r.get("option"),
                "color": color,
                "size": size,
            },

            "user_info": {
                "encrypted_id": r["encrypted_user_id"],
                "nickname": r["reviewer_nickname"],
                "level": r["reviewer_level"],
                "gender": r["reviewer_gender"],
                "height_cm": r["reviewer_height_cm"],
                "weight_kg": r["reviewer_weight_kg"],
            },

            "review_data": {
                "type": r["review_type"],
                "text": zlib.compress(r["review_text"].encode("utf-8")),
                "is_compressed": True,
                "has_photo": len(r.get("photo_urls", [])) > 0,
                "photo_urls": r.get("photo_urls", []),
                "like_count": r["like_count"],
            }
        })

    if cleaned:
        db.reviews.insert_many(cleaned, ordered=False)

    print(f"{filepath} → {len(cleaned)}개 삽입")

print("\n최종 확인")
print(f"products 총 문서 수: {db.products.count_documents({})}")
print(f"reviews 총 문서 수:  {db.reviews.count_documents({})}")

target_product_ids = [
    "202620", "903340", "1420730", "1841764", "1848166",
    "1999668", "1999677", "4314937", "4874594", "4956002",
    "324416", "540421", "996499", "1982990", "2034137",
    "2035287", "2122566", "2442409", "3083117", "3727165", "4587753"
]

result = db.reviews.delete_many({
    "product_id": {"$in": target_product_ids}
})

print(f"삭제된 리뷰 수: {result.deleted_count}")

import json
import zlib
from pymongo import MongoClient
from datetime import datetime


client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

# 기존 reviews 전체 삭제
db.reviews.drop()
print(f"reviews 삭제 완료")

import json
import zlib
from pymongo import MongoClient
from datetime import datetime

client = MongoClient("mongodb+srv://ays04_db_user:epdpsvmfhwprxm@cluster0.sftlrje.mongodb.net/?appName=Cluster0")
db = client["musinsa_db"]

product_files = [
    "202620_product_details.json", "903340_product_details.json",
    "1420730_product_details.json", "1841764_product_details.json",
    "1848166_product_details.json", "1999668_product_details.json",
    "1999677_product_details.json", "4314937_product_details.json",
    "4874594_product_details.json", "4956002_product_details.json",
    "324416_product_details.json", "540421_product_details.json",
    "996499_product_details.json", "1982990_product_details.json",
    "2034137_product_details.json", "2035287_product_details.json",
    "2122566_product_details.json", "2442409_product_details.json",
    "3083117_product_details.json", "3727165_product_details.json",
    "4587753_product_details.json"
]

print("products 적재")
for filepath in product_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    product = data["product_detail"]
    result = db.products.update_one(
        {"product_id": str(product["product_id"])},
        {"$set": {**product, "product_id": str(product["product_id"])}},
        upsert=True
    )
    status = "삽입" if result.upserted_id else "업데이트"
    print(f"[{status}] {product['product_id']} - {product['product_name']}")

review_files = [
    "202620_reviews.json", "903340_reviews.json",
    "1420730_reviews.json", "1841764_reviews.json",
    "1848166_reviews.json", "1999668_reviews.json",
    "1999677_reviews.json", "4314937_reviews.json",
    "4874594_reviews.json", "4956002_reviews.json",
    "324416_reviews.json", "540421_reviews.json",
    "996499_reviews.json", "1982990_reviews.json",
    "2034137_reviews.json", "2035287_reviews.json",
    "2122566_reviews.json", "2442409_reviews.json",
    "3083117_reviews.json", "3727165_reviews.json",
    "4587753_reviews.json"
]

def parse_option(option_str):
    if option_str and "·" in option_str:
        parts = option_str.split("·")
        return parts[0].strip(), parts[1].strip()
    return None, None

def parse_date(date_str):
    if not date_str:
        return None
    try:
        return datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        return None

print("\nreviews 적재")
for filepath in review_files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    reviews = data["reviews"]
    cleaned = []

    for r in reviews:
        review_text = r.get("review_text")
        if not review_text:
            continue

        color, size = parse_option(r.get("option"))
        actual_rating = None if r.get("rating") == 0.0 else r.get("rating")
        date_obj = parse_date(r.get("date"))

        cleaned.append({
            "product_id": str(r["product_id"]),
            "review_id":  str(r["review_id"]),
            "date":       date_obj,
            "rating":     actual_rating,
            "purchase_info": {
                "option_raw": r.get("option"),
                "color":      color,
                "size":       size,
            },
            "user_info": {
                "encrypted_id": r["encrypted_user_id"],
                "nickname":     r["reviewer_nickname"],
                "level":        r["reviewer_level"],
                "gender":       r["reviewer_gender"],
                "height_cm":    r["reviewer_height_cm"],
                "weight_kg":    r["reviewer_weight_kg"],
            },
            "review_data": {
                "type":            r.get("review_type"),
                "text_compressed": zlib.compress(review_text.encode("utf-8")),
                "is_compressed":   True,
                "has_photo":       len(r.get("photo_urls", [])) > 0,
                "like_count":      r.get("like_count", 0),
            }
        })

    if cleaned:
        try:
            db.reviews.insert_many(cleaned, ordered=False)
            print(f"{filepath} → {len(cleaned)}개 삽입")
        except Exception as e:
            print(f"{filepath} 삽입 중 오류 발생: {e}")

print("\n최종 확인")
print(f"products 총 문서 수: {db.products.count_documents({})}")
print(f"reviews 총 문서 수:  {db.reviews.count_documents({})}")

# 현재 컬렉션별 용량 확인
stats = db.command("collstats", "reviews")
print(f"reviews 크기: {stats['size'] / 1024 / 1024:.1f} MB")
print(f"reviews 문서 수: {stats['count']}")

stats2 = db.command("collstats", "products")
print(f"products 크기: {stats2['size'] / 1024 / 1024:.1f} MB")